/* ==========================================================================
   SUPERLIGA FRONTIER — DICCIONARIO MAESTRO
   Fuente única de verdad para todo el texto fijo de la web.

   Orden de los valores en cada clave:
     0 es · 1 en · 2 pt · 3 it · 4 fr · 5 ja · 6 ko · 7 pl · 8 bg · 9 sr

   CRITERIOS DE TRADUCCIÓN (esto no son traducciones literales)
   ─────────────────────────────────────────────────────────────
   · Terminología futbolística REAL de cada país, no calcada del español:
     "Clasificación" es Standings / Classifica / Classement / 順位表 / 순위표 /
     Tabela / Класиране, no "Classification".
   · "Jornada" es Matchday / Giornata / Journée / 節 / 라운드 / Kolejka.
   · "Goleadores" es Top scorers / Marcatori / Buteurs / 得点ランキング.
   · Jerga propia de la liga (jugadores verdes, tope salarial, reroll) se
     traduce con el término que usa la comunidad de cada idioma, no palabra
     por palabra.
   · NOMBRES PROPIOS (clubes, jugadores, managers) NUNCA se traducen: se
     transliteran en los idiomas de alfabeto distinto. Viven en el JSON, no
     aquí. Ver sfNameSet() en i18n.js.
   · Abreviaturas y siglas (POR/DEF/MED/DEL, ES/EN/FR, GF/GC) no pasan por
     traducción: "DEL" leído como preposición española daba "OF" en inglés.
   ========================================================================== */
(function () {
'use strict';

window.SF_DICT_LANGS = ['es','en','pt','it','fr','ja','ko','pl','bg','sr'];

window.SF_DICT = {

/* ─────────────────── NAVEGACIÓN Y ESTRUCTURA ─────────────────── */
'nav.clas':        ['Clasificación','Standings','Classificação','Classifica','Classement','順位表','순위표','Tabela','Класиране','Табела'],
'nav.resultados':  ['Resultados','Results','Resultados','Risultati','Résultats','試合結果','경기 결과','Wyniki','Резултати','Резултати'],
'nav.equipos':     ['Equipos','Teams','Equipas','Squadre','Équipes','チーム','팀','Drużyny','Отбори','Тимови'],
'nav.goleadores':  ['Goleadores','Top scorers','Marcadores','Marcatori','Buteurs','得点ランキング','득점 순위','Strzelcy','Голмайстори','Стрелци'],
'nav.noticias':    ['Noticias','News','Notícias','Notizie','Actualités','ニュース','뉴스','Aktualności','Новини','Вести'],
'nav.leyendas':    ['Leyendas','Legends','Lendas','Leggende','Légendes','レジェンド','레전드','Legendy','Легенди','Легенде'],
'nav.faq':         ['FAQ','FAQ','FAQ','FAQ','FAQ','よくある質問','자주 묻는 질문','FAQ','Въпроси','Питања'],
'nav.copa':        ['Copa','Cup','Taça','Coppa','Coupe','カップ','컵','Puchar','Купа','Куп'],
'skip.content':    ['Saltar al contenido','Skip to content','Saltar para o conteúdo','Vai al contenuto','Aller au contenu','本文へスキップ','본문으로 건너뛰기','Przejdź do treści','Към съдържанието','Пређи на садржај'],
'scroll':          ['Scroll','Scroll','Deslizar','Scorri','Défiler','スクロール','스크롤','Przewiń','Скрол','Скрол'],

/* ─────────────────── HERO ─────────────────── */
'hero.line1':   ['No sabes lo que te pierdes','You have no idea what you are missing','Não sabes o que estás a perder','Non sai cosa ti stai perdendo','Tu ne sais pas ce que tu rates','この面白さ、知らないままでいいのか','당신이 놓치고 있는 것','Nie wiesz, co tracisz','Не знаеш какво изпускаш','Не знаш шта пропушташ'],
'hero.line2':   ['hasta que lo vives','until you live it','até o viveres','finché non lo vivi','tant que tu ne l’as pas vécu','体験するまでは','직접 겪기 전까지는','dopóki tego nie przeżyjesz','докато не го изживееш','док то не доживиш'],
'hero.desc':    ['La liga competitiva de Inazuma Eleven: Victory Road, gestionada por la comunidad. Jugadores verdes, tope salarial y cero tácticas de RNG: aquí nadie gana por suerte de invocación.','The competitive Inazuma Eleven: Victory Road league, run by its own community. Green-tier players, a salary cap and no RNG tactics: nobody wins here on summoning luck.','A liga competitiva de Inazuma Eleven: Victory Road, gerida pela comunidade. Jogadores verdes, teto salarial e zero táticas de RNG: aqui ninguém ganha por sorte na invocação.','La lega competitiva di Inazuma Eleven: Victory Road, gestita dalla community. Giocatori verdi, tetto salariale e zero tattiche RNG: qui nessuno vince per fortuna nell’evocazione.','La ligue compétitive d’Inazuma Eleven: Victory Road, gérée par sa communauté. Joueurs verts, plafond salarial et zéro tactique RNG : ici personne ne gagne grâce à la chance d’invocation.','コミュニティが運営するイナズマイレブン ヴィクトリーロードの競技リーグ。緑レア選手、サラリーキャップ、RNG戦術の禁止。ここでは召喚運では勝てません。','커뮤니티가 직접 운영하는 이나즈마 일레븐: 빅토리 로드 경쟁 리그. 그린 등급 선수, 샐러리 캡, RNG 전술 금지. 이곳에서는 소환 운으로 이길 수 없습니다.','Liga competytywna Inazuma Eleven: Victory Road prowadzona przez społeczność. Zieloni zawodnicy, limit płac i zero taktyk opartych na losowości: tutaj nikt nie wygrywa dzięki szczęściu w przywołaniu.','Състезателната лига по Inazuma Eleven: Victory Road, управлявана от общността. Зелени играчи, таван на заплатите и нула RNG тактики: тук никой не печели с късмет при призоваването.','Такмичарска лига Inazuma Eleven: Victory Road, коју води сама заједница. Зелени играчи, платни лимит и ниједна RNG тактика: овде нико не побеђује захваљујући срећи при призивању.'],
'hero.cta':     ['Únete al Discord','Join the Discord','Entra no Discord','Entra nel Discord','Rejoins le Discord','Discordに参加','디스코드 참여하기','Dołącz na Discordzie','Влез в Discord','Придружи се Discord-у'],
'hero.cta2':    ['Ver la clasificación','See the standings','Ver a classificação','Vedi la classifica','Voir le classement','順位表を見る','순위표 보기','Zobacz tabelę','Виж класирането','Погледај табелу'],
'hero.enjuego': ['En juego','Under way','A decorrer','In corso','En cours','開催中','진행 중','W toku','В ход','У току'],

/* ─────────────────── MÉTRICAS ─────────────────── */
'stats.equipos':    ['Equipos activos','Active teams','Equipas ativas','Squadre attive','Équipes actives','参加チーム','활동 팀','Aktywne drużyny','Активни отбори','Активни тимови'],
'stats.jugadores':  ['Jugadores','Players','Jogadores','Giocatori','Joueurs','選手','선수','Zawodnicy','Играчи','Играчи'],
'stats.comps':      ['Competiciones','Competitions','Competições','Competizioni','Compétitions','大会数','대회','Rozgrywki','Състезания','Такмичења'],
'stats.temporada':  ['Temporada','Season','Temporada','Stagione','Saison','シーズン','시즌','Sezon','Сезон','Сезона'],
'stats.jornada':    ['Jornada','Matchday','Jornada','Giornata','Journée','節','라운드','Kolejka','Кръг','Коло'],

/* ─────────────────── REGLAS ─────────────────── */
'pillars.kicker': ['El argumento','What sets us apart','O argumento','Il punto','Ce qui nous distingue','リーグの根幹','우리의 차별점','Nasz argument','Аргументът','Оно што нас издваја'],
'pillars.title':  ['Cuatro reglas y ninguna excepción','Four rules, zero exceptions','Quatro regras e nenhuma exceção','Quattro regole e nessuna eccezione','Quatre règles, aucune exception','4つのルール、例外なし','네 가지 규칙, 예외는 없음','Cztery zasady i żadnych wyjątków','Четири правила и нула изключения','Четири правила и ниједан изузетак'],
'pillars.lede':   ['En el competitivo del juego gana quien más ha invocado. Aquí no: el azar existe una sola vez, en la invocación inicial, y a partir de ahí nadie puede tocar, cambiar ni mejorar nada.','In the game’s own competitive scene, whoever summoned the most wins. Not here: luck applies once, at the initial summon, and from that point nobody can touch, change or upgrade anything.','No competitivo do jogo ganha quem mais invocou. Aqui não: o acaso existe uma só vez, na invocação inicial, e a partir daí ninguém pode mexer, mudar ou melhorar nada.','Nel competitivo del gioco vince chi ha evocato di più. Qui no: il caso esiste una sola volta, nell’evocazione iniziale, e da lì nessuno può toccare, cambiare o migliorare nulla.','Dans le compétitif du jeu, c’est celui qui a le plus invoqué qui gagne. Pas ici : le hasard n’intervient qu’une fois, à l’invocation initiale, et ensuite personne ne peut toucher, changer ni améliorer quoi que ce soit.','ゲーム本編の対戦では、召喚を多く回した者が勝ちます。ここは違います。運が関わるのは最初の召喚だけ。そこから先は誰も手を加えられません。','게임 내 경쟁전에서는 소환을 많이 돌린 사람이 이깁니다. 여기서는 다릅니다. 운은 최초 소환 단 한 번뿐이고, 그 뒤로는 누구도 손댈 수 없습니다.','W trybie rywalizacji w grze wygrywa ten, kto więcej przywoływał. Tu nie: losowość działa tylko raz, przy pierwszym przywołaniu, a potem nikt nic nie ruszy, nie zmieni ani nie ulepszy.','В състезателния режим на играта печели онзи, който е призовавал най-много. Тук не е така: случайността се намесва само веднъж, при първоначалното призоваване, и оттам нататък никой не може да пипа, променя или подобрява нищо.','У такмичарском режиму саме игре побеђује онај ко је највише призивао. Овде не: срећа постоји само једном, при почетном призивању, а након тога нико не може ништа да дира, мења ни унапређује.'],
'pillars.1.title': ['Solo jugadores verdes','Green-tier players only','Apenas jogadores verdes','Solo giocatori verdi','Joueurs verts uniquement','緑レア選手のみ','그린 등급 선수만','Tylko zieloni zawodnicy','Само зелени играчи','Само зелени играчи'],
'pillars.1.text':  ['Rareza mínima y pasivas tal y como salieron de la invocación. Sin reroll.','Lowest rarity, passives exactly as summoned. No rerolls.','Raridade mínima e passivas tal como saíram da invocação. Sem reroll.','Rarità minima e passive esattamente come sono uscite. Nessun reroll.','Rareté minimale et passifs tels qu’ils sont sortis. Aucun reroll.','最低レアリティ、パッシブは召喚時のまま。リロールなし。','최저 등급, 패시브는 소환된 그대로. 리롤 금지.','Najniższa rzadkość, pasywki dokładnie takie, jakie wypadły. Bez przerzutów.','Минимална рядкост и пасиви точно както са призовани. Без преразпределяне.','Минимална реткост и пасиви тачно онакви какви су призвани. Без пребацивања.'],
'pillars.2.title': ['Tope salarial','Salary cap','Teto salarial','Tetto salariale','Plafond salarial','サラリーキャップ','샐러리 캡','Limit płac','Таван на заплатите','Платни лимит'],
'pillars.2.text':  ['El mercado tiene techo por club. Ninguna plantilla acumula todo el talento.','Every club has a spending ceiling. No squad hoards all the talent.','O mercado tem teto por clube. Nenhum plantel acumula todo o talento.','Il mercato ha un tetto per club. Nessuna rosa accumula tutto il talento.','Le marché a un plafond par club. Aucun effectif ne concentre tout le talent.','クラブごとに上限あり。特定のチームが才能を独占できません。','구단별 지출 상한이 있습니다. 한 팀이 인재를 독식할 수 없습니다.','Każdy klub ma limit wydatków. Żadna kadra nie zgarnia całego talentu.','Всеки клуб има таван на разходите. Нито един състав не трупа всички таланти.','Сваки клуб има горњу границу. Ниједан састав не гомила сав таленат.'],
'pillars.3.title': ['Cero tácticas de RNG','Zero RNG tactics','Zero táticas de RNG','Zero tattiche RNG','Zéro tactique RNG','RNG戦術は禁止','RNG 전술 금지','Zero taktyk losowych','Нула RNG тактики','Ниједна RNG тактика'],
'pillars.3.text':  ['Nada que resuelva un partido por suerte. Decide el manager, no el azar.','Nothing that decides a match by luck. The manager decides, not chance.','Nada que resolva um jogo pela sorte. Decide o treinador, não o acaso.','Niente che decida una partita per fortuna. Decide l’allenatore, non il caso.','Rien qui décide un match par chance. C’est le manager qui décide, pas le hasard.','運で試合が決まる要素は排除。決めるのは監督であって偶然ではありません。','운으로 경기가 결정되는 요소는 없습니다. 결정하는 것은 감독이지 우연이 아닙니다.','Nic, co rozstrzyga mecz losowo. Decyduje menedżer, nie przypadek.','Нищо, което решава мач с късмет. Решава мениджърът, не случайността.','Ништа што меч решава срећом. Одлучује менаџер, а не случајност.'],
'pillars.4.title': ['Divisiones por nivel','Divisions by level','Divisões por nível','Divisioni per livello','Divisions par niveau','レベル別ディビジョン','수준별 디비전','Dywizje według poziomu','Дивизии по ниво','Дивизије по нивоу'],
'pillars.4.text':  ['Ascenso y descenso para que nadie compita fuera de su nivel real.','Promotion and relegation so nobody competes outside their real level.','Subida e descida para que ninguém compita fora do seu nível real.','Promozione e retrocessione perché nessuno giochi fuori dal proprio livello.','Montée et descente pour que personne ne joue hors de son niveau réel.','昇格と降格により、実力に合った相手と戦えます。','승격과 강등으로 누구도 실력에 맞지 않는 곳에서 경쟁하지 않습니다.','Awans i spadek, aby nikt nie grał poza swoim poziomem.','Изкачване и изпадане, за да не играе никой извън реалното си ниво.','Пласман и испадање како нико не би играо ван свог нивоа.'],
'rules.1.f1b': ['rerolls','rerolls','rerolls','reroll','rerolls','リロール','리롤','przerzutów','преразпределяния','пребацивања'],
'rules.2.tag': ['por club','per club','por clube','per club','par club','クラブあたり','구단당','na klub','на клуб','по клубу'],
'rules.3.tag': ['tácticas de azar','luck-based tactics','táticas de sorte','tattiche casuali','tactiques hasardeuses','運任せの戦術','운 기반 전술','taktyk losowych','тактики на късмет','тактика на срећу'],
'rules.4.tag': ['divisiones','divisions','divisões','divisioni','divisions','ディビジョン','디비전','dywizje','дивизии','дивизије'],
'rules.foot':  ['El reglamento completo (lesiones, plantillas de 20, ventanas de fichajes y sanciones) vive en el Discord.','The full rulebook (injuries, 20-man squads, transfer windows and sanctions) lives on the Discord.','O regulamento completo (lesões, plantéis de 20, janelas de transferências e sanções) está no Discord.','Il regolamento completo (infortuni, rose da 20, finestre di mercato e sanzioni) vive sul Discord.','Le règlement complet (blessures, effectifs de 20, fenêtres de transfert et sanctions) se trouve sur le Discord.','詳細なルール（負傷、20人枠、移籍期間、処分）はDiscordにあります。','전체 규정(부상, 20인 스쿼드, 이적 시장, 제재)은 디스코드에 있습니다.','Pełny regulamin (kontuzje, kadry 20-osobowe, okna transferowe i kary) znajdziesz na Discordzie.','Пълният правилник (контузии, състави от 20 души, трансферни прозорци и санкции) е в Discord.','Комплетан правилник (повреде, састави од 20, прелазни рокови и казне) налази се на Discord-у.'],
'rules.cta':   ['Ver todas las reglas','See all the rules','Ver todas as regras','Vedi tutte le regole','Voir toutes les règles','ルールをすべて見る','전체 규칙 보기','Zobacz wszystkie zasady','Виж всички правила','Погледај сва правила'],

/* ─────────────────── HISTORIA ─────────────────── */
'historia.title': ['Tres temporadas construyendo liga','Three seasons building a league','Três temporadas a construir liga','Tre stagioni a costruire una lega','Trois saisons à bâtir une ligue','リーグを築いた3シーズン','리그를 만들어 온 세 시즌','Trzy sezony budowania ligi','Три сезона в изграждане на лига','Три сезоне грађења лиге'],
'historia.lede':  ['Cada temporada ha añadido una pieza que la anterior no tenía: primero el formato, después las competiciones, ahora la continuidad. Esta es la evolución real, sin adornos.','Every season added a piece the previous one lacked: first the format, then the competitions, now continuity. This is the real evolution, no window dressing.','Cada temporada acrescentou uma peça que a anterior não tinha: primeiro o formato, depois as competições, agora a continuidade. Esta é a evolução real, sem adornos.','Ogni stagione ha aggiunto un pezzo che alla precedente mancava: prima il formato, poi le competizioni, ora la continuità. Questa è l’evoluzione reale, senza fronzoli.','Chaque saison a ajouté une pièce qui manquait à la précédente : d’abord le format, puis les compétitions, maintenant la continuité. Voici l’évolution réelle, sans fioritures.','各シーズンが前のシーズンに欠けていたものを足してきました。まず形式、次に大会、そして今は継続性です。これが飾らない実際の歩みです。','매 시즌 이전 시즌에 없던 것을 하나씩 더해 왔습니다. 먼저 형식, 그다음 대회, 이제는 연속성입니다. 꾸밈없는 실제 발자취입니다.','Każdy sezon dodawał element, którego brakowało poprzedniemu: najpierw format, potem rozgrywki, teraz ciągłość. To prawdziwa ewolucja, bez upiększeń.','Всеки сезон добавяше по нещо, което на предишния му липсваше: първо форматът, после състезанията, сега приемствеността. Това е реалната еволюция, без разкрасяване.','Свака сезона додала је део који претходној недостаје: прво формат, затим такмичења, сада континуитет. Ово је стварна еволуција, без улепшавања.'],
'historia.t1.tag':   ['El punto de partida','The starting point','O ponto de partida','Il punto di partenza','Le point de départ','出発点','출발점','Punkt wyjścia','Началната точка','Полазна тачка'],
'historia.t1.title': ['Una sola división y un reglamento que probar','One division and a rulebook to test','Uma só divisão e um regulamento por testar','Una sola divisione e un regolamento da provare','Une seule division et un règlement à tester','1つのディビジョンと試すべきルール','단일 디비전과 검증해야 할 규정','Jedna dywizja i regulamin do sprawdzenia','Една дивизия и правилник за изпитване','Једна дивизија и правилник који треба проверити'],
'historia.t1.f1':    ['Sin campeón','No champion','Sem campeão','Nessun campione','Sans champion','優勝者なし','우승팀 없음','Bez mistrza','Без шампион','Без шампиона'],
'historia.t1.f2':    ['competición','competition','competição','competizione','compétition','大会','대회','rozgrywki','състезание','такмичење'],
'historia.t1.f3':    ['Reglamento en pruebas','Rulebook in testing','Regulamento em testes','Regolamento in prova','Règlement à l’essai','ルール試験運用','규정 시범 운영','Regulamin testowany','Правилник в тестове','Правилник у пробној фази'],
'historia.t2.tag':   ['La temporada que sí se cerró','The season that did finish','A temporada que se concluiu','La stagione che si è chiusa','La saison qui s’est terminée','完走できたシーズン','끝까지 마친 시즌','Sezon, który się zakończył','Сезонът, който приключи','Сезона која је приведена крају'],
'historia.t2.title': ['De una competición a tres','From one competition to three','De uma competição a três','Da una competizione a tre','D’une compétition à trois','1大会から3大会へ','대회 하나에서 셋으로','Z jednych rozgrywek do trzech','От едно състезание към три','Од једног такмичења до три'],
'historia.t2.f1':    ['títulos repartidos','titles shared out','títulos distribuídos','titoli assegnati','titres distribués','タイトルを分け合った','나눠 가진 우승','rozdanych tytułów','раздадени титли','подељених титула'],
'historia.t2.f2':    ['competiciones','competitions','competições','competizioni','compétitions','大会','대회','rozgrywki','състезания','такмичења'],
'historia.t2.f3':    ['Temporada completada','Season completed','Temporada concluída','Stagione completata','Saison terminée','シーズン完走','시즌 완주','Sezon ukończony','Завършен сезон','Завршена сезона'],
'historia.t2.ver':   ['Ver campeones','See the champions','Ver campeões','Vedi i campioni','Voir les champions','優勝チームを見る','우승팀 보기','Zobacz mistrzów','Виж шампионите','Погледај шампионе'],
'historia.t3.tag':   ['En curso','Under way','A decorrer','In corso','En cours','進行中','진행 중','W toku','В ход','У току'],
'historia.t3.tag2':  ['Continuidad','Continuity','Continuidade','Continuità','Continuité','継続性','연속성','Ciągłość','Приемственост','Континуитет'],
'historia.t3.title': ['La primera que enlaza con la anterior','The first one to follow straight on','A primeira que liga com a anterior','La prima che si allaccia alla precedente','La première qui enchaîne avec la précédente','前シーズンから途切れず続く初めてのシーズン','이전 시즌과 곧바로 이어지는 첫 시즌','Pierwszy, który następuje zaraz po poprzednim','Първият, който продължава веднага след предишния','Прва која се надовезује на претходну'],
'historia.t3.f1':    ['Temporada consecutiva','Back-to-back season','Temporada consecutiva','Stagione consecutiva','Saison consécutive','連続開催','연속 개최','Sezon z rzędu','Пореден сезон','Узастопна сезона'],
'historia.t3.f2':    ['Staff asentado','Settled staff','Equipa consolidada','Staff consolidato','Équipe en place','運営体制の定着','안정된 운영진','Ustabilizowany sztab','Утвърден екип','Устаљен штаб'],
'historia.t3.f3':    ['3 jornadas semanales','3 matchdays a week','3 jornadas por semana','3 giornate a settimana','3 journées par semaine','週3節','주 3라운드','3 kolejki w tygodniu','3 кръга седмично','3 кола недељно'],
'historia.note':     ['El fundador, Franshu, ha jugado las tres temporadas como manager (Kirkwood, Ragnah y Criaturas de la Noche) antes de dedicarse por completo a organizar.','Founder Franshu played all three seasons as a manager (Kirkwood, Ragnah and Criaturas de la Noche) before devoting himself entirely to running the league.','O fundador, Franshu, jogou as três temporadas como treinador (Kirkwood, Ragnah e Criaturas de la Noche) antes de se dedicar totalmente a organizar.','Il fondatore, Franshu, ha giocato tutte e tre le stagioni da allenatore (Kirkwood, Ragnah e Criaturas de la Noche) prima di dedicarsi completamente all’organizzazione.','Le fondateur, Franshu, a joué les trois saisons comme manager (Kirkwood, Ragnah et Criaturas de la Noche) avant de se consacrer entièrement à l’organisation.','創設者のFranshuは、運営に専念する前に3シーズンとも監督として参加していました（Kirkwood、Ragnah、Criaturas de la Noche）。','창립자 Franshu는 운영에 전념하기 전 세 시즌 모두 감독으로 참가했습니다(Kirkwood, Ragnah, Criaturas de la Noche).','Założyciel Franshu grał we wszystkich trzech sezonach jako menedżer (Kirkwood, Ragnah i Criaturas de la Noche), zanim poświęcił się wyłącznie organizacji.','Основателят Franshu е играл и трите сезона като мениджър (Kirkwood, Ragnah и Criaturas de la Noche), преди да се посвети изцяло на организацията.','Оснивач Franshu играо је све три сезоне као менаџер (Kirkwood, Ragnah и Criaturas de la Noche) пре него што се потпуно посветио организацији.'],

/* ─────────────────── SECCIONES ─────────────────── */
'resenas.kicker':   ['Voces de la comunidad','Voices from the community','Vozes da comunidade','Voci della community','Voix de la communauté','コミュニティの声','커뮤니티의 목소리','Głosy społeczności','Гласове от общността','Гласови заједнице'],
'resenas.title':    ['Lo que dicen los managers','What the managers say','O que dizem os treinadores','Cosa dicono gli allenatori','Ce que disent les managers','監督たちの声','감독들의 이야기','Co mówią menedżerowie','Какво казват мениджърите','Шта кажу менаџери'],
'sec.clas.kicker':  ['Liga regular','Regular season','Fase regular','Stagione regolare','Saison régulière','レギュラーシーズン','정규 시즌','Sezon zasadniczy','Редовен сезон','Регуларна сезона'],
'sec.clas':         ['Clasificación','Standings','Classificação','Classifica','Classement','順位表','순위표','Tabela','Класиране','Табела'],
'sec.resultados.kicker': ['Jornada a jornada','Matchday by matchday','Jornada a jornada','Giornata per giornata','Journée après journée','節ごとの結果','라운드별 결과','Kolejka po kolejce','Кръг по кръг','Коло по коло'],
'sec.resultados':   ['Resultados','Results','Resultados','Risultati','Résultats','試合結果','경기 결과','Wyniki','Резултати','Резултати'],
'sec.copa.kicker':  ['Grupos + eliminatorias','Groups + knockout','Grupos + eliminatórias','Gironi + eliminazione diretta','Groupes + phase finale','グループ+決勝トーナメント','조별리그 + 토너먼트','Grupy + faza pucharowa','Групи + елиминации','Групе + нокаут фаза'],
/* Nombre oficial confirmado por el cliente (no es la traducción literal que
   había antes). Esta clave se reutiliza en TODA la web para "Copa Fútbol
   Frontier", no sólo en el título de esta sección. */
'sec.copa':         ['Copa Fútbol Frontier','Frontier Football Cup','Copa de Futebol Frontier','Coppa Calcio Frontier','Coupe de Football Frontier','フロンティア・フットボールカップ','프런티어 풋볼컵','Puchar Futbolu Frontier','Купа Футбол Фронтиър','Фудбалски куп Фронтиер'],
'sec.equipos.kicker': ['Los clubes','The clubs','Os clubes','I club','Les clubs','クラブ一覧','클럽','Kluby','Клубовете','Клубови'],
'sec.equipos':      ['Equipos','Teams','Equipas','Squadre','Équipes','チーム','팀','Drużyny','Отбори','Тимови'],
'sec.goleadores.kicker': ['El único número que importa','The only number that matters','O único número que importa','L’unico numero che conta','Le seul chiffre qui compte','唯一意味のある数字','유일하게 중요한 숫자','Jedyna liczba, która się liczy','Единственото число, което има значение','Једини број који је важан'],
'sec.goleadores':   ['Goleadores','Top scorers','Marcadores','Marcatori','Buteurs','得点ランキング','득점 순위','Strzelcy','Голмайстори','Стрелци'],
'sec.noticias.kicker': ['Redacción de la comunidad','Written by the community','Redação da comunidade','Redazione della community','Rédaction de la communauté','コミュニティ編集部','커뮤니티 편집팀','Redakcja społeczności','Редакция на общността','Редакција заједнице'],
'sec.noticias':     ['Noticias','News','Notícias','Notizie','Actualités','ニュース','뉴스','Aktualności','Новини','Вести'],
'sec.leyendas.kicker': ['Salón de la fama','Hall of fame','Salão da fama','Hall of fame','Temple de la renommée','殿堂','명예의 전당','Galeria sław','Зала на славата','Кућа славних'],
'sec.leyendas':     ['Leyendas de la comunidad','Community legends','Lendas da comunidade','Leggende della community','Légendes de la communauté','コミュニティのレジェンド','커뮤니티의 레전드','Legendy społeczności','Легенди на общността','Легенде заједнице'],
'sec.staff.kicker': ['¿Quién gestiona esto?','Who runs all this?','Quem gere isto?','Chi gestisce tutto questo?','Qui gère tout ça ?','運営しているのは誰？','누가 운영하나요?','Kto tym zarządza?','Кой управлява това?','Ко ово води?'],
'sec.staff':        ['Equipo organizador','The organising team','Equipa organizadora','Team organizzatore','Équipe organisatrice','運営チーム','운영 팀','Zespół organizacyjny','Организационен екип','Организациони тим'],
'sec.faq.kicker':   ['Antes de preguntar en Discord','Before you ask on Discord','Antes de perguntar no Discord','Prima di chiedere su Discord','Avant de demander sur Discord','Discordで質問する前に','디스코드에 묻기 전에','Zanim zapytasz na Discordzie','Преди да питаш в Discord','Пре него што питаш на Discord-у'],
'sec.faq':          ['Preguntas frecuentes','Frequently asked questions','Perguntas frequentes','Domande frequenti','Questions fréquentes','よくある質問','자주 묻는 질문','Najczęstsze pytania','Често задавани въпроси','Често постављана питања'],
'staff.lede':       ['Seis personas que empezaron jugando y acabaron organizando. Todas siguen compitiendo con su club: nadie dirige la liga desde fuera de ella.','Six people who started out playing and ended up organising. All of them still compete with their own club: nobody runs this league from the outside.','Seis pessoas que começaram a jogar e acabaram a organizar. Todas continuam a competir com o seu clube: ninguém dirige a liga de fora dela.','Sei persone che hanno iniziato giocando e sono finite a organizzare. Tutte competono ancora con il proprio club: nessuno dirige la lega dall’esterno.','Six personnes qui ont commencé en jouant et ont fini par organiser. Toutes compétitionnent encore avec leur club : personne ne dirige la ligue de l’extérieur.','プレイヤーとして始まり、運営に回った6人。全員が今も自分のクラブで戦っています。外部から運営している人はいません。','선수로 시작해 운영까지 맡게 된 여섯 명. 모두 여전히 자기 구단으로 경쟁합니다. 리그 밖에서 운영하는 사람은 없습니다.','Sześć osób, które zaczęły od grania, a skończyły na organizowaniu. Wszystkie nadal rywalizują ze swoim klubem: nikt nie kieruje ligą z zewnątrz.','Шестима души, които започнаха като играчи и стигнаха до организацията. Всички още се състезават със своя клуб: никой не ръководи лигата отвън.','Шест људи који су почели играјући, а завршили организујући. Сви и даље играју са својим клубом: нико не води лигу споља.'],
'leyendas.lede':    ['Dos nombres que la liga no habría sido la misma sin ellos. Uno por récord, el otro por haber escrito una frase que ya nadie olvida.','Two names without whom this league would not be the same. One for a record, the other for a line nobody has forgotten.','Dois nomes sem os quais a liga não seria a mesma. Um por recorde, o outro por ter escrito uma frase que já ninguém esquece.','Due nomi senza i quali la lega non sarebbe la stessa. Uno per un record, l’altro per una frase che nessuno dimentica.','Deux noms sans lesquels la ligue ne serait pas la même. L’un pour un record, l’autre pour une phrase que personne n’oublie.','この2人がいなければ、リーグは今の形ではありませんでした。ひとりは記録で、もうひとりは誰もが覚えている一言で。','이 두 사람이 없었다면 리그는 지금과 달랐을 것입니다. 한 명은 기록으로, 다른 한 명은 누구도 잊지 못하는 한마디로.','Dwa nazwiska, bez których liga nie byłaby taka sama. Jedno za rekord, drugie za zdanie, którego nikt nie zapomniał.','Две имена, без които лигата нямаше да е същата. Едното заради рекорд, другото заради реплика, която никой не забравя.','Два имена без којих лига не би била иста. Једно због рекорда, друго због реченице коју нико није заборавио.'],
'leyendas.d4rk.rank': ['Récord','Record','Recorde','Record','Record','記録','기록','Rekord','Рекорд','Рекорд'],
'leyendas.payo.rank': ['Folclore','Folklore','Folclore','Folclore','Folklore','語り草','전설의 한마디','Folklor','Фолклор','Фолклор'],
'leyendas.d4rk.role': ['Presidente · Superliga','President · Superliga','Presidente · Superliga','Presidente · Superliga','Président · Superliga','会長 · スーペルリーガ','회장 · 수페르리가','Prezes · Superliga','Президент · Суперлига','Председник · Суперлига'],
'leyendas.payo.role': ['Presidente · Superliga','President · Superliga','Presidente · Superliga','Presidente · Superliga','Président · Superliga','会長 · スーペルリーガ','회장 · 수페르리가','Prezes · Superliga','Президент · Суперлига','Председник · Суперлига'],
'leyendas.d4rk.text': ['Según Steam Ladder, el jugador con más horas registradas en Inazuma Eleven: Victory Road de Europa y de España, y el segundo del mundo entero.','According to Steam Ladder, the player with the most recorded hours in Inazuma Eleven: Victory Road across Europe and Spain, and second worldwide.','Segundo o Steam Ladder, o jogador com mais horas registadas em Inazuma Eleven: Victory Road da Europa e de Espanha, e o segundo do mundo inteiro.','Secondo Steam Ladder, il giocatore con più ore registrate a Inazuma Eleven: Victory Road in Europa e in Spagna, e il secondo al mondo.','Selon Steam Ladder, le joueur avec le plus d’heures enregistrées sur Inazuma Eleven: Victory Road en Europe et en Espagne, et deuxième au monde.','Steam Ladderによれば、イナズマイレブン ヴィクトリーロードのプレイ時間がヨーロッパとスペインで1位、世界でも2位の選手です。','Steam Ladder 기준, 이나즈마 일레븐: 빅토리 로드 플레이 시간이 유럽과 스페인에서 1위, 전 세계 2위인 플레이어입니다.','Według Steam Ladder gracz z największą liczbą zarejestrowanych godzin w Inazuma Eleven: Victory Road w Europie i Hiszpanii oraz drugi na świecie.','Според Steam Ladder играчът с най-много регистрирани часове в Inazuma Eleven: Victory Road в Европа и Испания и вторият в целия свят.','Према Steam Ladder-у, играч са највише забележених сати у Inazuma Eleven: Victory Road у Европи и Шпанији, и други на свету.'],
'leyendas.payo.text': ['Dirigida a david.gonzzalezc, presidente del Alpino, antes de un enfrentamiento directo. La frase se quedó, y ya forma parte del folclore de la liga.','Aimed at david.gonzzalezc, president of Alpino, before a head-to-head. The line stuck, and it is now part of league folklore.','Dirigida a david.gonzzalezc, presidente do Alpino, antes de um confronto direto. A frase ficou e já faz parte do folclore da liga.','Rivolta a david.gonzzalezc, presidente dell’Alpino, prima di uno scontro diretto. La frase è rimasta ed è ormai folclore della lega.','Adressée à david.gonzzalezc, président d’Alpino, avant un duel direct. La phrase est restée et fait désormais partie du folklore de la ligue.','直接対決の前に、Alpino会長のdavid.gonzzalezcへ向けられた一言。この台詞は残り、今ではリーグの語り草です。','직접 대결을 앞두고 Alpino 회장 david.gonzzalezc를 향해 던진 한마디. 이 말은 남았고, 이제 리그의 전설이 되었습니다.','Skierowane do david.gonzzalezc, prezesa Alpino, przed bezpośrednim starciem. Zdanie zostało i należy już do folkloru ligi.','Отправено към david.gonzzalezc, президент на Alpino, преди пряк сблъсък. Репликата остана и вече е част от фолклора на лигата.','Упућено david.gonzzalezc-у, председнику Alpino-а, пред директан дуел. Реченица је остала и већ је део фолклора лиге.'],
'leyendas.d4rk.s1t': ['Europa','Europe','Europa','Europa','Europe','ヨーロッパ','유럽','Europa','Европа','Европа'],
'leyendas.d4rk.s2t': ['Mundial','Worldwide','Mundial','Mondiale','Mondial','世界','전 세계','Świat','Световно','Свет'],
'leyendas.d4rk.s3t': ['Club','Club','Clube','Club','Club','クラブ','클럽','Klub','Клуб','Клуб'],
'leyendas.payo.s1t': ['Club','Club','Clube','Club','Club','クラブ','클럽','Klub','Клуб','Клуб'],
'leyendas.payo.s2t': ['Estatus','Status','Estatuto','Stato','Statut','ステータス','상태','Status','Статус','Статус'],
'leyendas.payo.s2d': ['Cita oficial','Official quote','Citação oficial','Citazione ufficiale','Citation officielle','公式の名言','공식 명언','Cytat oficjalny','Официален цитат','Званични цитат'],

/* ─────────────────── TABLA Y CUADROS ─────────────────── */
'th.pos':   ['Pos','Pos','Pos','Pos','Pos','順位','순위','Poz','Поз','Поз'],
'th.equipo':['Equipo','Team','Equipa','Squadra','Équipe','チーム','팀','Drużyna','Отбор','Тим'],
'th.pj':    ['PJ','MP','J','G','MJ','試合','경기','M','М','У'],
'th.g':     ['G','W','V','V','V','勝','승','Z','П','П'],
'th.e':     ['E','D','E','N','N','分','무','R','Р','Н'],
'th.p':     ['P','L','D','P','D','敗','패','P','З','И'],
'th.gf':    ['GF','GF','GM','GF','BP','得点','득점','B+','ГЗ','ГД'],
'th.gc':    ['GC','GA','GS','GS','BC','失点','실점','B-','ГП','ГП'],
'th.dg':    ['DG','GD','DG','DR','Diff','得失','득실','+/-','ГР','ГР'],
'th.pts':   ['Pts','Pts','Pts','Pti','Pts','点','점','Pkt','Т','Б'],
'th.forma': ['Forma','Form','Forma','Forma','Forme','調子','최근 5경기','Forma','Форма','Форма'],
'bracket.playoff.kicker': ['Fase final','Final phase','Fase final','Fase finale','Phase finale','決勝ラウンド','파이널 라운드','Faza finałowa','Финална фаза','Завршна фаза'],
'bracket.playoff.title':  ['Cuadro de Play Off / Play In','Play Off / Play In bracket','Quadro de Play Off / Play In','Tabellone Play Off / Play In','Tableau Play Off / Play In','プレーオフ / プレーイン トーナメント表','플레이오프 / 플레이인 대진표','Drabinka Play Off / Play In','Схема Плейоф / Плей-ин','Жреб плеј-оф / плеј-ин'],

/* ─────────────────── PIE, BUSCADOR, FICHAS ─────────────────── */
'footer.tagline':   ['No sabes lo que te pierdes hasta que lo vives.','You have no idea what you are missing until you live it.','Não sabes o que estás a perder até o viveres.','Non sai cosa ti stai perdendo finché non lo vivi.','Tu ne sais pas ce que tu rates tant que tu ne l’as pas vécu.','体験するまで、この面白さは分かりません。','직접 겪기 전까지는 무엇을 놓치고 있는지 알 수 없습니다.','Nie wiesz, co tracisz, dopóki tego nie przeżyjesz.','Не знаеш какво изпускаш, докато не го изживееш.','Не знаш шта пропушташ док то не доживиш.'],
'footer.liga':      ['Liga','League','Liga','Lega','Ligue','リーグ','리그','Liga','Лига','Лига'],
'footer.comunidad': ['Comunidad','Community','Comunidade','Community','Communauté','コミュニティ','커뮤니티','Społeczność','Общност','Заједница'],
'footer.legal':     ['Legal','Legal','Legal','Legale','Mentions légales','法的事項','법적 고지','Informacje prawne','Правна информация','Правне информације'],
'footer.terminos':  ['Términos y privacidad','Terms and privacy','Termos e privacidade','Termini e privacy','Conditions et confidentialité','利用規約とプライバシー','약관 및 개인정보','Regulamin i prywatność','Условия и поверителност','Услови и приватност'],
'footer.disclaimer':['El arte de jugadores y equipos pertenece a Level-5, creadores de Inazuma Eleven. Superliga Frontier es un proyecto de fans sin ánimo de lucro: no genera ningún beneficio económico.','Player and team artwork belongs to Level-5, creators of Inazuma Eleven. Superliga Frontier is a non-profit fan project: it generates no financial gain whatsoever.','A arte de jogadores e equipas pertence à Level-5, criadores de Inazuma Eleven. A Superliga Frontier é um projeto de fãs sem fins lucrativos: não gera qualquer benefício económico.','Le illustrazioni di giocatori e squadre appartengono a Level-5, creatori di Inazuma Eleven. Superliga Frontier è un progetto amatoriale senza scopo di lucro: non genera alcun profitto.','Les illustrations des joueurs et des équipes appartiennent à Level-5, créateurs d’Inazuma Eleven. Superliga Frontier est un projet de fans à but non lucratif : il ne génère aucun bénéfice.','選手とチームのアートワークはイナズマイレブンの制作元であるレベルファイブに帰属します。スーペルリーガ・フロンティアは非営利のファンプロジェクトであり、一切の収益を生みません。','선수와 팀 아트워크의 권리는 이나즈마 일레븐 제작사인 Level-5에 있습니다. 수페르리가 프론티어는 비영리 팬 프로젝트이며 어떠한 수익도 발생시키지 않습니다.','Grafiki zawodników i drużyn należą do Level-5, twórców Inazuma Eleven. Superliga Frontier to niekomercyjny projekt fanowski: nie przynosi żadnych korzyści finansowych.','Артът на играчите и отборите принадлежи на Level-5, създателите на Inazuma Eleven. Superliga Frontier е нестопански фен проект: не генерира никаква финансова изгода.','Уметност играча и тимова припада Level-5, творцима Inazuma Eleven. Superliga Frontier је непрофитни фански пројекат: не остварује никакву зараду.'],
'search.placeholder': ['Buscar equipos, jugadores, noticias…','Search teams, players, news…','Procurar equipas, jogadores, notícias…','Cerca squadre, giocatori, notizie…','Rechercher équipes, joueurs, actualités…','チーム・選手・ニュースを検索…','팀, 선수, 뉴스 검색…','Szukaj drużyn, zawodników, wiadomości…','Търсене на отбори, играчи, новини…','Претражи тимове, играче, вести…'],
'search.todo':      ['Todo','All','Tudo','Tutto','Tout','すべて','전체','Wszystko','Всичко','Све'],
'search.equipos':   ['Equipos','Teams','Equipas','Squadre','Équipes','チーム','팀','Drużyny','Отбори','Тимови'],
'search.jugadores': ['Jugadores','Players','Jogadores','Giocatori','Joueurs','選手','선수','Zawodnicy','Играчи','Играчи'],
'search.noticias':  ['Noticias','News','Notícias','Notizie','Actualités','ニュース','뉴스','Aktualności','Новини','Вести'],
'search.empty':     ['Sin resultados para esta búsqueda','No results for this search','Sem resultados para esta pesquisa','Nessun risultato per questa ricerca','Aucun résultat pour cette recherche','該当する結果がありません','검색 결과가 없습니다','Brak wyników dla tego wyszukiwania','Няма резултати за това търсене','Нема резултата за ову претрагу'],
'lang.title':       ['Idioma','Language','Idioma','Lingua','Langue','言語','언어','Język','Език','Језик'],
'champs.note':      ['Campeones calculados sobre la clasificación final archivada de esa temporada y el resultado de la final de Copa. Toca un club para abrir su ficha.','Champions derived from that season’s archived final standings and the Cup final result. Tap a club to open its profile.','Campeões calculados a partir da classificação final arquivada dessa temporada e do resultado da final da Taça. Toca num clube para abrir a ficha.','Campioni calcolati sulla classifica finale archiviata di quella stagione e sul risultato della finale di Coppa. Tocca un club per aprirne la scheda.','Champions calculés à partir du classement final archivé de cette saison et du résultat de la finale de Coupe. Touche un club pour ouvrir sa fiche.','そのシーズンの最終順位表とカップ決勝の結果から算出した優勝チームです。クラブをタップすると詳細が開きます。','해당 시즌의 최종 순위표와 컵 결승 결과로 산출한 우승팀입니다. 구단을 누르면 상세 정보가 열립니다.','Mistrzowie wyliczeni na podstawie zarchiwizowanej tabeli końcowej tego sezonu i wyniku finału Pucharu. Dotknij klubu, aby otworzyć profil.','Шампионите са изчислени по архивираното крайно класиране за този сезон и резултата от финала за Купата. Докосни клуб, за да отвориш профила му.','Шампиони израчунати на основу архивиране коначне табеле те сезоне и резултата финала Купа. Додирни клуб да отвориш профил.'],
'snd.on':           ['Activar música','Turn music on','Ativar música','Attiva la musica','Activer la musique','音楽をオンにする','음악 켜기','Włącz muzykę','Включи музиката','Укључи музику'],
'snd.off':          ['Silenciar música','Mute music','Silenciar música','Silenzia la musica','Couper la musique','音楽をオフにする','음악 끄기','Wycisz muzykę','Заглуши музиката','Искључи музику']

};
})();
